// components/dashboard/welcome-banner.tsx
export function WelcomeBanner() {
  return (
    <div className="flex items-center justify-between rounded-lg bg-primary/10 px-4 py-3">
      <div>
        <h2 className="text-lg font-semibold">Welcome back, Student</h2>
        <p className="text-sm text-muted-foreground">
          Here's what's happening with your courses today.
        </p>
      </div>
    </div>
  );
}

// components/dashboard/WelcomeBanner.vue
<template>
  <div class="mb-8 rounded-lg border bg-card p-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold tracking-tight mb-1">
          Welcome back, Student
        </h1>
        <p class="text-muted-foreground">
          Current semester: {{ semesterName }}
        </p>
      </div>
      <div class="hidden md:block">
        <div class="text-primary h-16 w-16 flex items-center justify-center text-2xl font-bold">
          T
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  semesterName: {
    type: String,
    required: true
  }
})
</script>
